.TH INTRAEL 1 "November 21, 2011" "" "Intrael application server"

.SH NAME
intrael \- Computer vision for the web

..SH SYNOPSIS
.TX
\fBintrael\fP [\fIoptions\fP]
     		
.br

.SH DESCRIPTION
The \fBintrael\fP server processes the depth stream from the Kinect, identifies objects and measures several of their properties. The collected data for each frame are then made available to network clients through HTTP wrapped in JSON arrays. Its main purpose is to enable web developers to develop computer vision apps using javascript & HTML. The protocol used is standard HTTP though so other languages can take advantage of it as well. It also provides the raw camera frames as JPEG snapshots or MJPEG streams. 

.SH OPTIONS
.TP 
\fB-p \fIPORT\fR
Sets the port the server should listen to. Default is 6661.
.TP 
\fB-l \fIADDRESS\fR
 Sets the address the server should listen to. Default is INADDR_ANY.
.TP 
\fB-d \fIDEVICE\fR
 Sets the kinect device to use. You can either supply an index id(0-9) or the serial of a specific kinect. The special value "list" prints the serials of all kinected kinects. Default is 0, first device by index.
.TP 
\fB-j \fIMODE\fR
 Sets the JPEG quality. Range is 25-75. Default is 50.
.TP 
\fB-m \fIMASK\fR
 The first 3 bits of the provided integer MASK toggle Server Sent Events for data and MJPEG for grayscale(depth)JPEG and rgb JPEG outputs, respectively. SSE does not, as of this writing, support cross origin on any browser so the only way to test it is by using the option "-t" below. Range is 0-7. Default is 6 which means: poll for data(no SSE) and MJPEG streams for both cameras.
.TP
\fB-s \fISECRET\fR
 Sets a secret passphrase to be used for securing the live config functionality of the server.  A value of "0" enables the feature but without the need to authenticate. Live config changes are disabled by default.
.TP
\fB-f \fIFILE\fR
 Sets the file to load  the background reference frame from. The format is standard pgm(the extension is NOT added automatically).
.TP
\fB-F \fIFILE\fR
 Sets the file to dump the background reference file to.
.TP
\fB-o \fIFILE\fR
 Reads the contents of the specified file to form a whitelist of origins that can issue requests to the server. Default is to allow all origins.
.TP
\fB-i \fIFILE\fR
 Reads the contents of the specified file to form a whitelist of IPs that can connect to the server from a comma separated list. Default is to allow all IPs.
.TP
\fB-t \fIFILE\fR
 Serves the contents of the specified file on special path /3 with html Content-type(See USAGE below). Default is not to serve any static contents.
.TP
\fB-n\fR
 No rgb video. Disables the rgb camera which gives a small performance boost.
.TP
\fB-b\fR
 Big messages. By default the max size for the JSON messages of the server is 4KB which can fit ~25 concurrent blobs per message. This option raises the limit to 16KB allowing ~100 blobs.
.TP 
\fB-v\fP
 Prints the version of the program.

.TP
\fB The following options can also be changed live through http requests\fP


.TP
\fB-e \fIINT\fR
 Background extraction. This option controls the mode of operation for the background extraction. A value of 0 disables extraction, everything scanned withing the boundaries described by the following options will be taken into account. A positive value forces the server to create a reference frame(controlled by the -r option, see below) and report just the differences on subsequent frames. A negative value the server also utiilizes a background frame but scans with depth boundaries(-z,-Z options) relative to the background frame. Eg along with -z 30 -Z 120 the server will scan for blobs that are from 30 to 120 mm from the wall(or whatever was captured in the background frame). The absolute value of the option adds a safety margin that helps to clear noise that results from the instability of depth reporting from the kinect. Start low and raise until the result satisfies. The default value is 0, no extraction.
.TP
\fB-r \fIFRAMES\fR
 Set the number of frames to take into account while creating the background reference frame. Range is 1-999. Processing multiple frames leads to better quality of the reference frame and the extraction process(See above). While constructing the reference frame the kinect's led will blink orange-red. A value of 1 won't actually process a frame but just reset the depth maps and clear up the depth buffer used for generating the grayscale JPEG(see USAGE). Range is 1-9999. The default is 32, about one second worth of frames.
.TP
\fB-x \fIPIXEL\fR
 Set the lower bound for the X axis scan. Range is 0-632. Will be rounded to a multiple of 8. Default is 0.
.TP
\fB-X \fIPIXEL\fR
 Set the higher bound for the X axis scan. Range is 0-632. Will be rounded to a multiple of 8. Default is 632.
.TP
\fB-y \fIPIXEL\fR
 Set the lower bound for the Y axis scan. Range is 0-478. Default is 0.
.TP
\fB-Y \fIPIXEL\fR
 Set the higher bound for the Y axis scan. Range is 0-479. Default is 479.
.TP
\fB-z \fIMILLIMETRES\fR
 Set the low threshold for the Y axis(depth) scan in mm. Range is 0-9999. Default is 30.
.TP
\fB-Z \fIMILLIMETRES\fR
 Set the high threshold for the Y axis scan in mm. Range is 1-9999. Default is 1340.
.TP
\fB-c \fIPIXELS\fR
 Set the minimum pixel count for an object to be reported. Range is 1-300000. Default is 1024.
.TP
\fB-C \fIPIXELS\fR
 Set the maximum pixel count for an object to be reported. Default is 0, check disabled.
.TP
\fB-f \fIDUMMY\fR
 When used in the context of live config(See below), it forces a reload of the reference frame from/if the file was specified on startup. DUMMY means that an argument has to be passed in the query string but is not taken into account.
.TP
\fB-F \fIDUMMY\fR
 When used in the context of live config(See below), it forces a dump of the reference frame to/if the file was specified on startup with the -F option. DUMMY means that an argument has to be passed in the query string but is not taken into account.
.TP
\fB-o \fIDUMMY\fR
 When used in the context of live config(See below), it forces a reload of the origin list from/if the file was specified on startup with the -o option. DUMMY means that an argument has to be passed in the query string but is not taken into account.
.TP
\fB-i \fIDUMMY\fR
 When used in the context of live config(See below), it forces a reload of the IP list from/if the file was specified on startup with the -i option. DUMMY means that an argument has to be passed in the query string but is not taken into account.
.TP
\fB-t \fIDUMMY\fR
 When used in the context of live config(See below), it forces a reload of the contents for static file serving from the file that was specified on startup. DUMMY means that an argument has to be passed in the query string but is not taken into account.
.TP
\fB-a \fIANGLE\fR
 Moves the motor to the specified angle. After the motor moves to the specified position(Indicated by the last element of the HEADER, see below) you should reconstruct the reference frame(-r option) if using background extraction. Range is -31 to 31.

.SH USAGE

The server speaks the standard http protocol. Clients retrieve the data through xmlhttprequests or the <img> tag. Requests for any path that starts with anything else than /1 and /2(And even that if you have explicitly disabled RGB with the -n option) return the tracking data for the current frame in the form of a JSON array that's composed of an 16 element header followed by several 32 element packs, one for every detected blob. The formats for these are detailed in the next sections. The following paths are special:

.TP
\fB/0?\fIQUERY_STRING\fR
 This path allows live configuration changes to be performed to the server. All alowable command line options can be used here in the form of a query string eg. /0?z=1000&Z=2000 would force the engine to threshold from 1000 to 2000 millimetres. By default this functionality is disabled. You can enable it without authentication by specifying the option -s 0 on the command line. If -s is set to a string authentication is enabled which works as follows. The second element from the header in the JSON data output of the server(see HEADER FORMAT below) is a timestamp that must be concatenated with  the string provided to -s (<SECRET><TIMESTAMP>) and the result md5 hashed. The hash must then be passed along with the rest of the query arguments as an s=<HASH> for the commands to take effect. After every succesful request the hash timestamp will change requiring a repeat of the process for subsequent requests. The design does not take into account concurrent requests from multiple clients.
.TP
\fB/1\fR
 This path provides 640x480 grayscale JPEGs created from the, thresholded, depth input. If multipart is enabled through the -m option(it is by default) you'll get an MJPEG stream else single snapshots per request. {WARNING} The grayscale stream is built as part of the blob tracking process. The implication of this is that you must concurently poll for the JSON data or else the JPEG stream will stall. The implication of this is that you should set the image src after you start polling for the JSON data.
.TP
\fB/2\fR
 This path provides 640x480 RGB JPEGs created from the video camera input. If multipart is enabled through the -m option(it is by default) you'll get an MJPEG stream else single snapshots per request. You'll have to manually shift parts of the depth JPEGs to match the rgb camera using the value provided as the last element of the data pack for each blob(See BLOB FORMAT below). The x and y shifting modifiers can be derived from this value like this: y=<VAL>/640 and x=<VAL>%640.  If the rgb functionality was disabled with the use of the -n command line option, the regular JSON response will be returned instead.
.TP
\fB/3\fR
 This path serves a static html file if it was specified on the command line with the -t option, otherwise it's the default JSON response.
.TP
\fBNOTICE\fR
 If several requests to the server have exactly the same paths, the browser will serialize the requests lowering the effective rate for each request. To avoid that you should request a unique path for every simultaneous request. Only the first character matters for selecting the type of data returned. So, a path of "/test3243434" will return the tracking data, a "/1dfdfdfdf" will return grayscale JPEGs and a "0ertdgf?z=..." will perform live changes.



.SH "HEADER FORMAT"
 
The first 16 elements of the JSON array from the server's response will always be present, even if no blobs were detected. Each of its elements are described below by index:

.TP
\fB0\fP
Timestamp of the current frame as provided by the kinect.
.TP
\fB1\fP
Timestamp of the last configuration change. See path /0 above.
.TP
\fB2\fP
Background extraction mode. See -e option.
.TP
\fB3\fP
Low x axis bound for the raster scan. See -x option.
.TP
\fB4\fP
High x axis bound for the raster scan. See -X option.
.TP
\fB5\fP
Low y axis bound for the raster scan. See -y option.
.TP
\fB6\fP
High y axis bound for the raster scan. See -Y option.
.TP
\fB7\fP
Low depth threshold. See -z option.
.TP
\fB8\fP
High depth threshold. See -Z option.
.TP
\fB9\fP
Low pixel count limit for blob filtering. See -c option.
.TP
\fB10\fP
High pixel count limit for blob filtering. See -C option.
.TP
\fB11\fP
Accelerometer X value in G.
.TP
\fB12\fP
Accelerometer Y value in G.
.TP
\fB13\fP
Accelerometer Z value in G.
.TP
\fB14\fP
Motor angle as reported by the kinect.
.TP
\fB15\fP
Motor state. 0-Not moving, 4-Moving.

.SH "BLOB FORMAT"

 After the 16 elements of the header comes the information for the detected blobs in fixed length(32) element packs. The structure of these packs is described below by index:

.TP
\fB0\fP
x coordinate of the geometric center of the object.
.TP
\fB1\fP
y coordinate of the geometric center of the object.
.TP
\fB2\fP
Average depth of all object's pixels.
.TP
\fB3\fP
Background depth at the geometric center of the object.
.TP
\fB4\fP
x coordinate of the leftmost point of the object.
.TP
\fB5\fP
y coordinate of the leftmost point of the object.
.TP
\fB6\fP
Depth of the leftmost point of the object.
.TP
\fB7\fP
Background depth at the leftmost point of the object.
.TP
\fB8\fP
x coordinate of the rightmost point of the object.
.TP
\fB9\fP
y coordinate of the rightmost point of the object.
.TP
\fB10\fP
Depth of the rightmost point of the object.
.TP
\fB11\fP
Background depth at the rightmost point of the object.
.TP
\fB12\fP
x coordinate of the topmost point of the object.
.TP
\fB13\fP
y coordinate of the topmost point of the object.
.TP
\fB14\fP
Depth of the topmost point of the object.
.TP
\fB15\fP
Background depth at the topmost point of the object.
.TP
\fB16\fP
x coordinate of the bottommost point of the object.
.TP
\fB17\fP
y coordinate of the bottommost point of the object.
.TP
\fB18\fP
Depth of the bottommost point of the object.
.TP
\fB19\fP
Background depth at the bottommost point of the object.
.TP
\fB20\fP
x coordinate of the point of the object nearest to the camera.
.TP
\fB21\fP
y coordinate of the point of the object nearest to the camera.
.TP
\fB22\fP
Depth of the point of the object nearest to the camera.
.TP
\fB23\fP
Background depth at the point of the object nearest to the camera.
.TP
\fB24\fP
x coordinate of the point of the object furthest from the camera.
.TP
\fB25\fP
y coordinate of the point of the object furthest from the camera.
.TP
\fB26\fP
Depth of the point of the object furthest from the camera.
.TP
\fB27\fP
Background depth at the point of the object furthest from the camera.
.TP
\fB28\fP
Pixel count of the object.
.TP
\fB29\fP
The count of continuous horizontal lines(runs) that compose the object.
.TP
\fB30\fP
Y coordinate that indicates the area of greatest concentration of runs.
.TP
\fB31\fP
Shifting modifier for the rgb mask (See the description for path /2 on USAGE). 


.SH "EXAMPLES"

Check http://www.intrael.com

.SH "SEE ALSO"

Check http://www.openkinect.org


.SH "AUTHOR"

Yannis Gravezas (wizgrav@gmail.com)

.SH "LICENSE"

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License v3 for more details.

You should have received a copy of the GNU General Public License v3
along with this program.  If not, see <http://www.gnu.org/licenses/gpl-3.0.txt>.

